stages:
  - build-environment
  - test

variables:
  pgpassword: postgres
  pguser: postgres
  databaseName: bucketmanager

services:
  - name: postgres:latest
    alias: postgres
    variables:
      POSTGRES_USER: $pguser
      POSTGRES_PASSWORD: $pgpassword
    

cache:
  paths:
    - /var/lib/docker
    - .m2/repository

buildEnvironment:
  stage: build-environment
  image: postgres:latest
  script:
    - export PGPASSWORD=$pgpassword
    - psql -h postgres -U $pguser -c "CREATE DATABASE $databaseName;"
    - databases=$(psql -h postgres -U $pguser -c "SELECT datname FROM pg_database;" | grep -w $databaseName)
    - if [[ -z "$databases" ]]; then echo "O banco de dados $databaseName não está na lista.";exit 1; else echo "O banco de dados $databaseName está na lista."; fi


test:
  stage: test
  image: maven:latest
  script:
    - export SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$databaseName

