stages:
  - build
  - compile
  - codeQuality
  - unitTest
  - integrationTest
  - jar
  - testJar
  - pushDockerImage

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:latest

cache:
  paths:
    - .m2/repository

build:
  stage: build
  rules:
    - changes:
        - src/**/*
  script:
    - mvn clean install

compile:
  stage: compile
  rules:
    - changes:
        - src/**/*
  script:
    - mvn compile

codeQuality:
  stage: codeQuality
  rules:
    - changes:
        - src/**/*
  script:
    - mvn checkstyle:checkstyle
    - cat target/checkstyle-result.xml
  artifacts:
    paths:
      - target/checkstyle-result.xml

test:
  stage: unitTest
  rules:
    - changes:
        - src/**/*
  script:
    - mvn test -Punit-tests
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml


buildJar:
  stage: jar
  rules:
    - changes:
        - src/**/*
  script:
    - mvn package
  artifacts: 
    when: on_success
    paths:
      - target/bucket-manager.jar

testJar:
  stage: testJar
  rules:
    - changes:
        - src/**/*
  image: openjdk:17-alpine
  script:
    - cp target/bucket-manager.jar app.jar
    - java -jar app.jar &

pushDockerImage:
  stage: pushDockerImage
  image: docker:20.10.10
  only:
    changes:
      - src/**/*
    refs:
      - master
  cache:
    paths:
      - .docker
  services:
    - docker:20.10.10-dind   
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest