spring:
  datasource:
    url: dsadsaas
    username: dasasddsa
    password: dasdsadssda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

aws:
  bucket:
    region: us-east-1
    endpoint: http://localhost:4566
    names: bucket-test1, bucket-test2
    maxSize: 9318621

  enable:
    notification: false
    autoCreateBuckets: true
    metrics: true

  metrics:
    names: metric1, metric2, BucketSizeBytes

  sns:
    region: us-east-1
    endpoint: http://localhost:4566/
    file:
      deleted:
        arn: adsdsasdasda
      uploaded:
        arn: dasdsaasddsa
